### ISSUE TITLE
add a single macro

### ISSUE THREAD

**Issue by kermith72** [guillaumewatteeux/ansible-centreon#2]
when I add a macro to a host, it is not added

` exemple code 

    tasks: 
    - name: Add host to Centreon
      centreon_host:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        name: "Server"
        alias: "Server Monitoring"
        ipaddr: "127.0.0.1"
        hostgroups:
          - Linux-Server
        hosttemplates:
          - OS-Linux-SNMP-custom
          - App-DB-MySQL
        macros:
          - name: MACRO1
             value: value1
        instance: Central
        status: enabled
        state: present
        applycfg: False
      delegate_to: localhost`

it works with several macros

**Comment by guillaumewatteeux** [comment]
Hi @kermith72,

Could you retry with quoted value ?

```
macros:
  - name: "MACRO1"
     value: "value1"
```

On my production env, I use this code to add a macros.
```
- role: centreon
     centreon_host_macros:
       - name: "MATTERMOST_CHAN"
          value: "{{ _centreon_notification_mattermost_chan }}"
```

And code: https://github.com/guillaumewatteeux/ansible-role-centreon/blob/532db51d115598ecd72b92b076d308e11fce6f52/tasks/main.yml#L29
