### ISSUE TITLE
centreon_hosts should allow null values

### ISSUE THREAD

**Issue by C-Bam** [guillaumewatteeux/ansible-centreon#5]
**Issue**
```
- name: Add host to Centreon
      centreon_host:
        url: "{{ centreon_url }}"
        username: "{{ centreon_api_user }}"
        password: "{{ centreon_api_pass }}"
        #...#
        # Without hostgroups
```

**Actual Result**
```
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
		#...#		
            "hostgroups": null,
            "hostgroups_action": "add",
		#...#
    },
    "msg": "Create: "
}
```

**Expected Result**
Ignore the hostgroup

**Hints**

I narrowed down to centreon_host.py (maybe line 284 block)

```python
centreon.host.add(
                name,
                alias,
                ipaddr,
                hosttemplates,
                instance,
                hostgroups
            )
```
